
package client.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Mysrv", targetNamespace = "http://myws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Mysrv {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTime", targetNamespace = "http://myws/", className = "client.jaxws.GetTime")
    @ResponseWrapper(localName = "getTimeResponse", targetNamespace = "http://myws/", className = "client.jaxws.GetTimeResponse")
    @Action(input = "http://myws/Mysrv/getTimeRequest", output = "http://myws/Mysrv/getTimeResponse")
    public String getTime();
    
    

}
