
package client.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MysrvService", targetNamespace = "http://myws/", wsdlLocation = "file:/Users/Andric/Documents/dev/Eclipse/WebService-Jaxws/MysrvService.wsdl")
public class MysrvService
    extends Service
{

    private final static URL MYSRVSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYSRVSERVICE_EXCEPTION;
    private final static QName MYSRVSERVICE_QNAME = new QName("http://myws/", "MysrvService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/Andric/Documents/dev/Eclipse/WebService-Jaxws/MysrvService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYSRVSERVICE_WSDL_LOCATION = url;
        MYSRVSERVICE_EXCEPTION = e;
    }

    public MysrvService() {
        super(__getWsdlLocation(), MYSRVSERVICE_QNAME);
    }

    public MysrvService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYSRVSERVICE_QNAME, features);
    }

    public MysrvService(URL wsdlLocation) {
        super(wsdlLocation, MYSRVSERVICE_QNAME);
    }

    public MysrvService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYSRVSERVICE_QNAME, features);
    }

    public MysrvService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MysrvService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Mysrv
     */
    @WebEndpoint(name = "MysrvPort")
    public Mysrv getMysrvPort() {
        return super.getPort(new QName("http://myws/", "MysrvPort"), Mysrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Mysrv
     */
    @WebEndpoint(name = "MysrvPort")
    public Mysrv getMysrvPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://myws/", "MysrvPort"), Mysrv.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYSRVSERVICE_EXCEPTION!= null) {
            throw MYSRVSERVICE_EXCEPTION;
        }
        return MYSRVSERVICE_WSDL_LOCATION;
    }
    
    

}
